venvv/Warehouse/apps/ware/urls.py
from django.urls import path
from django.conf.urls import url
from django.urls.conf import re_path
from .views import ProductListView
from .import views
from .views import (
    add_to_cart,
    # delete_from_cart,
    my_profile
)

app_name = 'ware'

urlpatterns = [
    path('all-products/', ProductListView.as_view(), name='all_products'),
    path('profile/', views.my_profile, name="profile"),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name="add_to_cart"),
    path('all-products/order-summary', views.order_details, name="order_summary")
]

venvv/Warehouse/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('ware.urls')),
]

venvv/Warehouse/apps/ware/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.conf import settings

from django.db.models.deletion import CASCADE
from django.db.models.signals import post_save
from django.db.models.signals import post_save
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

CATEGORY = (
    ('print', 'Принтер'),
    ('proj', 'Проектор'),
    ('laptop', 'Ноутбук'),
)

class Product(models.Model):
    product_name = models.CharField('Название товара', max_length=100)
    category = models.CharField('Категория', max_length=10, default='print', choices=CATEGORY)
    product_number = models.IntegerField('Количество товара', default=0)

    def __str__(self):
        return self.product_name


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)



class Order(models.Model):
    user = models.ForeignKey(Profile, on_delete=CASCADE)
    order_product_name = models.ManyToManyField(Product, null=True)
    ordered_product_num = models.IntegerField("Количество занятого товара", default=0)
    date_ordered = models.DateTimeField(null=True)
    ebooks = models.ManyToManyField(Product, blank=True)
    stripe_id = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    user_profile, created = Profile.objects.get_or_create(user=instance)

    if user_profile.stripe_id is None or user_profile.stripe_id == '':
        new_stripe_id = stripe.Customer.create(email=instance.email)
        user_profile.stripe_id = new_stripe_id['id']
        user_profile.save()


post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)


    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])
    # def __str__(self):
    #     return self.owner

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

venvv/Warehouse/apps/ware/views.py
from django.views.generic import ListView
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404



from .extras import generate_order_id

import datetime

from .models import Order, Product, Profile

class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'product/all_products.html'


def get_user_pending_order(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    user_profile = get_object_or_404(Profile, user=request.user)
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    product = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    if product.product_number > 1:
        quantity = product.product_number-1
        user_profile.ordered_product_num + quantity
        user_order.items.add(user_profile.ordered_product_num, product.product_name, product.date_ordered)
        user_profile.save()

    messages.info(request, "item added to cart")
    return redirect(reverse('ware:all_products'))


# @login_required()
# def delete_from_cart(request, item_id):
#     item_to_delete = OrderItem.objects.filter(pk=item_id)
#     if item_to_delete.exists():
#         item_to_delete[0].delete()
#         messages.info(request, "Item has been deleted")
#     return redirect(reverse('ware:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'order/order_summary.html', context)


def my_profile(request):
	my_user_profile = Profile.objects.filter(user=request.user).first()
	my_orders = Order.objects.filter()
	context = {
		'my_orders': my_orders
	}

	return render(request, "profile/profile.html", context)

venvv/Warehouse/templates/base.html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
	<title>{% block title %} Мой сайт {% endblock %}</title>
</head>
<body>

{% block navbar %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#" style="color: #8c52ff;">Godzilla's page</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Домой</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
    </div>
    {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <p class="nav-link active">Привет <strong>{{ user.username }}</strong> </p>
        </li>
        <li class="nav-item">
          <a class="btn btn-light"  aria-current="page" href="{% url 'ware:profile' %}">Личный кабинет</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Выход</a>
        </li>
      </ul> 
  </div>
    {% else %}
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mb-2 mb-lg">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Вход</a>
          <a class="nav-link active" style="color: #8c52ff; font-weight:bold" aria-current="page" href="#">Регистрация</a>
        </li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>

{% endblock %}

	{% block content %} 

	test


	 {% endblock %}

</body>
</html>

venvv/Warehouse/templates/order/order_summary.html
{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ product.product_number }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'product:all_products' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

venvv/Warehouse/templates/product/all_products.html
{% extends 'base.html' %}

    {% block title %} Список товаров {% endblock %}

    {% block content %}
 <head>
 </head>
    
    
    {% for product in products %}
    <div class="container mt-4">
      <div class="row">
        <div class="col-sm-4">
          <div class="card">
            <div class="card-header">{{ product.category }}</div>
            <div class="card-body">
              <h5 class="card-title">{{ product.product_name }}</h5>
              <p class="card-text">Количество: <strong>{{ product.product_number }} </strong></p>
              {% comment %} <form class="input-group mb-1" action="{% url 'ware:add_to_cart' product.id %}">
                <div class="input-group mb-1">
                  <div class="input-group-prepend">
                    <button type="submit" class="btn btn-outline-primary" type="button" id="inputGroupFileAddon03">Button</button>
                  </div>
                  <input type="submit" class="form-control" placeholder="Количество товара" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" aria-label="Number">
                </div>
              </form> {% endcomment %}
              <a href="{% url 'ware:add_to_cart' product.id %}" class="btn btn-primary">Занять</a>
              <a href="#" class="btn btn-success">Вернуть</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    

    {% endblock %}

venvv/Warehouse/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Дата взятия</th>
        <th>Товар</th>
        <th>Количество взятого товара</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>
        	 {% for name in my_orders %}
        		{{ name.order_product_name }}
      		{% endfor %} 
      	  </td>
          <td>
              {% for item in my_orders %}
              {{ item.ordered_product_num }}
              {% endfor %}
        </td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'ware:all_products' %}" class="btn btn-warning pull-left">
            {% if not order %}К списку товаров{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </table>
</div>

{% endblock content %}